---
- name: ensure packages are installed
  apt: name={{item}}
  with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2

- name: ensure database is created
  postgresql_db: name={{dbname}}
  sudo: yes
  sudo_user: postgres

- name: set up pgcrypto for the database
  postgresql_ext: name=pgcrypto db={{dbname}}
  sudo: yes
  sudo_user: postgres

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
  sudo: yes
  sudo_user: postgres

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo: yes
  sudo_user: postgres
