---
- name: ensure packages are installed
  apt: name={{item}}
  with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: ensure database is created
  postgresql_db: name={{dbname}}
  become: yes
  become_user: postgres
  become_method: sudo

- name: set up pgcrypto for the database
  postgresql_ext: name=pgcrypto db={{dbname}}
  become: yes
  become_user: postgres
  become_method: sudo

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
  become: yes
  become_user: postgres
  become_method: sudo

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres
  become_method: sudo
